export const refs = {
  body: document.querySelector('body'),
  searchInputRef: document.querySelector('.input'),
  galleryRef: document.querySelector('.gallery__container'),
  moviesContainerRef: document.querySelector('.gallery-home'),
  myLibraryContainerRef: document.querySelector('.gallery-my-library'),
  headerRef: document.querySelector('.header'),
  searchRef: document.querySelector('.search'),
  libraryBtnRef: document.querySelector('.header-library__buttons'),
  jsLibrary: document.querySelector('.js-library'),
  jsHome: document.querySelector('.js-home'),
  jsIcon: document.querySelector('.js-icon'),
  backdropRef: document.querySelector('.backdrop, .movie-modal-wrap'),
  footerBtnRef: document.querySelector('.footer__btn'),
  backToTopRef: document.querySelector('.backToTop'),
  // currentPage: document.querySelector('.current-page'),
  // prevPage: document.querySelector('.prev-page'),
  // nextPage: document.querySelector('.next-page'),
};
