export const refs = {
  body: document.querySelector('body'),
  searchInputRef: document.querySelector('.input'),
  galleryRef: document.querySelector('.gallery__container'),
  moviesContainerRef: document.querySelector('.gallery-home'),
  myLibraryContainerRef: document.querySelector('.gallery-my-library'),
  headerHome: document.querySelector('.header-home'),
  headerLibrary: document.querySelector('.header-library'),
  jsLibrary: document.querySelector('.header-home .js-library'),
  jsHome: document.querySelector('.header-library .js-home'),
  jsIcon: document.querySelector('.header-library .js-icon'),
  backdropRef: document.querySelector('.backdrop'),
  // currentPage: document.querySelector('.current-page'),
  // prevPage: document.querySelector('.prev-page'),
  // nextPage: document.querySelector('.next-page'),
};
